version: '3'
services:
  log-tailer:
    container_name: log-tailer
    build:
      dockerfile: Dockerfile
    environment:
      - SEND_LOGS=
      - LOG_TOKEN=
      - LOG_REGION=
      - SILENT_MODE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock