version: '3'
services:
  log-tailer:
    container_name: log-tailer
    build:
      dockerfile: Dockerfile
    environment:
      - HOSTNAME=testingDocker
      - API_KEY=240ba119-3124-49a9-babc-45fc50fbfbfa
      - LOG_REGION=eu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - disableLogging=true