version: '3'
services:
  log-tailer:
    container_name: log-tailer
    build:
      dockerfile: Dockerfile
    environment:
      - HOSTNAME=
      - API_KEY=
      - LOG_REGION=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - disablePostLogging=true